/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static java.lang.Integer.parseInt;
import proyecto.xd.Conexion;
import proyecto.xd.Inmueble;
import proyecto.xd.Inmueble_data;

/**
 *
 * @author julit
 */
public class ActualizarInmueble extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarInmueble
     */
    public ActualizarInmueble() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_salir = new javax.swing.JButton();
        b_guardar = new javax.swing.JButton();
        t_ndisponibilidad = new javax.swing.JTextField();
        l_ndisponibilidad = new javax.swing.JLabel();
        t_nambientes = new javax.swing.JTextField();
        l_nambientes = new javax.swing.JLabel();
        t_ndireccion = new javax.swing.JTextField();
        l_ndireccion = new javax.swing.JLabel();
        t_direcciona = new javax.swing.JTextField();
        l_direcciona = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        l_ncosto1 = new javax.swing.JLabel();
        t_ncosto1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_salir.setBackground(new java.awt.Color(0, 51, 102));
        b_salir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        b_salir.setForeground(new java.awt.Color(255, 255, 255));
        b_salir.setText("Salir");
        b_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });
        getContentPane().add(b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 70, 30));

        b_guardar.setBackground(new java.awt.Color(0, 51, 102));
        b_guardar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        b_guardar.setForeground(new java.awt.Color(255, 255, 255));
        b_guardar.setText("Guardar");
        b_guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(b_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 70, 30));

        t_ndisponibilidad.setBackground(new java.awt.Color(0, 51, 102));
        t_ndisponibilidad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ndisponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        t_ndisponibilidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_ndisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ndisponibilidadActionPerformed(evt);
            }
        });
        getContentPane().add(t_ndisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 170, -1));

        l_ndisponibilidad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ndisponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        l_ndisponibilidad.setText("Nueva dosponibilidad:");
        getContentPane().add(l_ndisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        t_nambientes.setBackground(new java.awt.Color(0, 51, 102));
        t_nambientes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_nambientes.setForeground(new java.awt.Color(255, 255, 255));
        t_nambientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_nambientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nambientesActionPerformed(evt);
            }
        });
        getContentPane().add(t_nambientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 170, -1));

        l_nambientes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_nambientes.setForeground(new java.awt.Color(255, 255, 255));
        l_nambientes.setText("Nueva Cant.Ambientes:");
        getContentPane().add(l_nambientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        t_ndireccion.setBackground(new java.awt.Color(0, 51, 102));
        t_ndireccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ndireccion.setForeground(new java.awt.Color(255, 255, 255));
        t_ndireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(t_ndireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, -1));

        l_ndireccion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ndireccion.setForeground(new java.awt.Color(255, 255, 255));
        l_ndireccion.setText("Nueva dirección:");
        getContentPane().add(l_ndireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        t_direcciona.setBackground(new java.awt.Color(0, 51, 102));
        t_direcciona.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_direcciona.setForeground(new java.awt.Color(255, 255, 255));
        t_direcciona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_direcciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_direccionaActionPerformed(evt);
            }
        });
        getContentPane().add(t_direcciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, -1));

        l_direcciona.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_direcciona.setForeground(new java.awt.Color(255, 255, 255));
        l_direcciona.setText("Ingrese dirección:");
        getContentPane().add(l_direcciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 51, 102));
        jTextArea1.setColumns(13);
        jTextArea1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(4);
        jTextArea1.setTabSize(6);
        jTextArea1.setText(" Ingrese el DNI de la  personaque deseas  actualizar");
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 220, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inmuebles");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 110, 46));

        l_ncosto1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ncosto1.setForeground(new java.awt.Color(255, 255, 255));
        l_ncosto1.setText("Nuevo costo:");
        getContentPane().add(l_ncosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        t_ncosto1.setBackground(new java.awt.Color(0, 51, 102));
        t_ncosto1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ncosto1.setForeground(new java.awt.Color(255, 255, 255));
        t_ncosto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_ncosto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ncosto1ActionPerformed(evt);
            }
        });
        getContentPane().add(t_ncosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_direccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_direccionaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_direccionaActionPerformed

    private void t_nambientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nambientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nambientesActionPerformed

    private void t_ndisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ndisponibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ndisponibilidadActionPerformed

    private void t_ncosto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ncosto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ncosto1ActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:

         Inmueble i = new Inmueble();

        try
        {
            Conexion cn = new Conexion("jdbc:mysql://localhost/inmobiliaria", "root", "");
            Inmueble_data inmueble = new Inmueble_data(cn);
            inmueble.actualizarInmueble(i, t_ndireccion.getText(), parseInt(t_nambientes.getText()), parseInt(t_ncosto1.getText()), parseInt(t_ndisponibilidad.getText()), t_direcciona.getText());
        }
        catch(Exception ex)
        {
            System.out.println("Error al insertar un inmueble: " + ex.getMessage());
        }

    }//GEN-LAST:event_b_guardarActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_b_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton b_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel l_direcciona;
    private javax.swing.JLabel l_nambientes;
    private javax.swing.JLabel l_ncosto1;
    private javax.swing.JLabel l_ndireccion;
    private javax.swing.JLabel l_ndisponibilidad;
    private javax.swing.JTextField t_direcciona;
    private javax.swing.JTextField t_nambientes;
    private javax.swing.JTextField t_ncosto1;
    private javax.swing.JTextField t_ndireccion;
    private javax.swing.JTextField t_ndisponibilidad;
    // End of variables declaration//GEN-END:variables
}
