/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import proyecto.xd.*;
/**
 *
 * @author julit
 */
public class ActualizarAlquiler extends javax.swing.JInternalFrame {

    String filtro = "Nombre";
    String filtro2 = "Direccion";
    private DefaultTableModel modelo;
    private DefaultTableModel modelo2;
    String filtro3 = "Nombre";
    
    private DefaultTableModel modelo3;
    /**
     * Creates new form ActualizarAlquiler
     */
    public ActualizarAlquiler() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_nnombre = new javax.swing.JTextField();
        l_nnombre = new javax.swing.JLabel();
        t_ninmueble = new javax.swing.JTextField();
        t_nombrea = new javax.swing.JTextField();
        b_guardar = new javax.swing.JButton();
        t_nfin = new javax.swing.JTextField();
        l_ncosto1 = new javax.swing.JLabel();
        b_salir = new javax.swing.JButton();
        l_nombrea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_ninicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        l_nambientes = new javax.swing.JLabel();
        l_ninmueble = new javax.swing.JLabel();
        l_ncosto2 = new javax.swing.JLabel();
        t_ncosto = new javax.swing.JTextField();
        l_ninquilino1 = new javax.swing.JLabel();
        t_ninquilino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        busquedap = new javax.swing.JTextField();
        combop = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablap = new javax.swing.JTable();
        botonp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboi = new javax.swing.JComboBox<>();
        busquedai = new javax.swing.JTextField();
        botoni7 = new javax.swing.JButton();
        tablai = new javax.swing.JScrollPane();
        i = new javax.swing.JTable();
        combo = new javax.swing.JComboBox<>();
        busqueda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botoon1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_nnombre.setBackground(new java.awt.Color(0, 51, 102));
        t_nnombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_nnombre.setForeground(new java.awt.Color(255, 255, 255));
        t_nnombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_nnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nnombreActionPerformed(evt);
            }
        });
        getContentPane().add(t_nnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 110, -1));

        l_nnombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_nnombre.setForeground(new java.awt.Color(255, 255, 255));
        l_nnombre.setText("Nuevo nombre:");
        getContentPane().add(l_nnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        t_ninmueble.setBackground(new java.awt.Color(0, 51, 102));
        t_ninmueble.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ninmueble.setForeground(new java.awt.Color(255, 255, 255));
        t_ninmueble.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_ninmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ninmuebleActionPerformed(evt);
            }
        });
        t_ninmueble.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ninmuebleKeyTyped(evt);
            }
        });
        getContentPane().add(t_ninmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 110, 20));

        t_nombrea.setBackground(new java.awt.Color(0, 51, 102));
        t_nombrea.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_nombrea.setForeground(new java.awt.Color(255, 255, 255));
        t_nombrea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_nombrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombreaActionPerformed(evt);
            }
        });
        getContentPane().add(t_nombrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, -1));

        b_guardar.setBackground(new java.awt.Color(0, 51, 102));
        b_guardar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        b_guardar.setForeground(new java.awt.Color(255, 255, 255));
        b_guardar.setText("Guardar");
        b_guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(b_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 620, 70, 30));

        t_nfin.setBackground(new java.awt.Color(0, 51, 102));
        t_nfin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_nfin.setForeground(new java.awt.Color(255, 255, 255));
        t_nfin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_nfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nfinActionPerformed(evt);
            }
        });
        getContentPane().add(t_nfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, -1));

        l_ncosto1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ncosto1.setForeground(new java.awt.Color(255, 255, 255));
        l_ncosto1.setText("Nueva fecha de fin:");
        getContentPane().add(l_ncosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        b_salir.setBackground(new java.awt.Color(0, 51, 102));
        b_salir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        b_salir.setForeground(new java.awt.Color(255, 255, 255));
        b_salir.setText("Salir");
        b_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });
        getContentPane().add(b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, 70, 30));

        l_nombrea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_nombrea.setForeground(new java.awt.Color(255, 255, 255));
        l_nombrea.setText("Nombre:");
        getContentPane().add(l_nombrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alquileres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 110, 46));

        t_ninicio.setBackground(new java.awt.Color(0, 51, 102));
        t_ninicio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ninicio.setForeground(new java.awt.Color(255, 255, 255));
        t_ninicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_ninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ninicioActionPerformed(evt);
            }
        });
        getContentPane().add(t_ninicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 110, -1));

        jScrollPane1.setWheelScrollingEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 51, 102));
        jTextArea1.setColumns(13);
        jTextArea1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(4);
        jTextArea1.setTabSize(6);
        jTextArea1.setText(" Ingrese el nombre del\nalquiler que deseas \nactualizar");
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 190, 90));

        l_nambientes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_nambientes.setForeground(new java.awt.Color(255, 255, 255));
        l_nambientes.setText("Nueva fecha de inicio:");
        getContentPane().add(l_nambientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        l_ninmueble.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ninmueble.setForeground(new java.awt.Color(255, 255, 255));
        l_ninmueble.setText("Nuevo inmueble:");
        getContentPane().add(l_ninmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        l_ncosto2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ncosto2.setForeground(new java.awt.Color(255, 255, 255));
        l_ncosto2.setText("Nuevo costo:");
        getContentPane().add(l_ncosto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        t_ncosto.setBackground(new java.awt.Color(0, 51, 102));
        t_ncosto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ncosto.setForeground(new java.awt.Color(255, 255, 255));
        t_ncosto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_ncosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ncostoActionPerformed(evt);
            }
        });
        t_ncosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ncostoKeyTyped(evt);
            }
        });
        getContentPane().add(t_ncosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 110, -1));

        l_ninquilino1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ninquilino1.setForeground(new java.awt.Color(255, 255, 255));
        l_ninquilino1.setText("Nuevo inquilino:");
        getContentPane().add(l_ninquilino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        t_ninquilino.setBackground(new java.awt.Color(0, 51, 102));
        t_ninquilino.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ninquilino.setForeground(new java.awt.Color(255, 255, 255));
        t_ninquilino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_ninquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ninquilinoActionPerformed(evt);
            }
        });
        t_ninquilino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ninquilinoKeyTyped(evt);
            }
        });
        getContentPane().add(t_ninquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 110, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Busquedas de alquileres");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 250, 46));

        busquedap.setBackground(new java.awt.Color(0, 51, 102));
        busquedap.setForeground(new java.awt.Color(255, 255, 255));
        busquedap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        busquedap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedapActionPerformed(evt);
            }
        });
        getContentPane().add(busquedap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 110, 20));

        combop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Nombre", "D.N.I" }));
        combop.setToolTipText("Seleccionar");
        combop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopActionPerformed(evt);
            }
        });
        getContentPane().add(combop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, 20));

        tablap.setBackground(new java.awt.Color(0, 51, 102));
        tablap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablap.setForeground(new java.awt.Color(255, 255, 255));
        tablap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "DNI", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablap.setRowHeight(30);
        tablap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablap);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 520, 160));

        botonp.setBackground(new java.awt.Color(0, 51, 102));
        botonp.setForeground(new java.awt.Color(255, 255, 255));
        botonp.setText("Buscar");
        botonp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpActionPerformed(evt);
            }
        });
        getContentPane().add(botonp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 70, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Busquedas de personas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 250, 46));

        comboi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Dirección", "Cantidad de ambientes" }));
        comboi.setToolTipText("Seleccionar");
        comboi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboiActionPerformed(evt);
            }
        });
        getContentPane().add(comboi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 120, 20));

        busquedai.setForeground(new java.awt.Color(255, 255, 255));
        busquedai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaiActionPerformed(evt);
            }
        });
        getContentPane().add(busquedai, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 120, -1));

        botoni7.setBackground(new java.awt.Color(0, 51, 102));
        botoni7.setForeground(new java.awt.Color(255, 255, 255));
        botoni7.setText("Buscar");
        botoni7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botoni7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoni7ActionPerformed(evt);
            }
        });
        getContentPane().add(botoni7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 70, 20));

        i.setBackground(new java.awt.Color(0, 51, 102));
        i.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        i.setForeground(new java.awt.Color(255, 255, 255));
        i.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Dirección", "Cantidad Ambientes", "Costo", "Disponibilidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        i.setRowHeight(30);
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iMouseClicked(evt);
            }
        });
        tablai.setViewportView(i);

        getContentPane().add(tablai, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 540, 160));

        combo.setBackground(new java.awt.Color(0, 51, 102));
        combo.setForeground(new java.awt.Color(255, 255, 255));
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Nombre", "Costo" }));
        combo.setToolTipText("Seleccionar");
        combo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 100, 20));

        busqueda.setBackground(new java.awt.Color(0, 51, 102));
        busqueda.setForeground(new java.awt.Color(255, 255, 255));
        busqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        busqueda.setCaretColor(new java.awt.Color(255, 255, 255));
        busqueda.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 110, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Busquedas de inmuebles");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 250, 46));

        botoon1.setBackground(new java.awt.Color(0, 51, 102));
        botoon1.setForeground(new java.awt.Color(255, 255, 255));
        botoon1.setText("Buscar");
        botoon1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botoon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoon1ActionPerformed(evt);
            }
        });
        getContentPane().add(botoon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 70, 80, 20));

        tabla.setBackground(new java.awt.Color(0, 51, 102));
        tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Fecha De Inicio", "Fecha De Fin", "Costo"
            }
        ));
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setRowHeight(30);
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 480, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1290, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_b_salirActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:

         Alquiler a = new Alquiler(t_nnombre.getText(), LocalDate.parse(t_ninicio.getText()), LocalDate.parse(t_nfin.getText()), parseInt(t_ncosto.getText()), parseInt(t_ninmueble.getText()), parseInt(t_ninquilino.getText()));

        try
        {
            Conexion cn = new Conexion("jdbc:mysql://localhost/inmobiliaria", "root", "");
            Alquiler_data ad = new Alquiler_data(cn);
            ad.actualizarAlquiler(a);
        }
        catch(Exception ex)
        {
            System.out.println("Error al insertar un inmueble: " + ex.getMessage());
        }
        
        String mensaje = "¡Alquiler actualizado con exito!";
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_b_guardarActionPerformed

    private void t_ninmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ninmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ninmuebleActionPerformed

    private void t_ninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ninicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ninicioActionPerformed

    private void t_nombreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombreaActionPerformed

    private void t_nfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nfinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nfinActionPerformed

    private void t_ncostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ncostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ncostoActionPerformed

    private void t_ninquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ninquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ninquilinoActionPerformed

    private void t_nnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nnombreActionPerformed

    private void combopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopActionPerformed
        // TODO add your handling code here:
        if (combop.getSelectedItem() == "Nombre")
        {
            filtro = "nombre";
        }
        if (combop.getSelectedItem() == "D.N.I")
        {
            filtro = "DNI";
        }

    }//GEN-LAST:event_combopActionPerformed

    private void botonpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpActionPerformed
        // TODO add your handling code here:
        try
        {
            Conexion cn = new Conexion("jdbc:mysql://localhost/inmobiliaria", "root", "");
            persona p = new persona();
            persona_data personadata = new persona_data(cn);
            //personadata.obtenerPersonasPorFiltro(filtro, busqueda.getText());

            List<persona> per = personadata.obtenerPersonasPorFiltro(filtro, busquedap.getText());

            modelo = (DefaultTableModel) tablap.getModel();
            modelo.setRowCount(0);
            Object[] fila = new Object[modelo.getColumnCount()];

            for (int i = 0; i < per.size(); i++) {
                fila[0] = per.get(i).getId();
                fila[1] = per.get(i).getNombre().toUpperCase();
                fila[2] = per.get(i).getDni();
                fila[3] = per.get(i).getCelular();

                modelo.addRow(fila);
            }

        }
        catch(Exception e)
        {
            e.getMessage();
        }
    }//GEN-LAST:event_botonpActionPerformed

    private void tablapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapMouseClicked
        // TODO add your handling code here:
        int seleccion = tablap.rowAtPoint(evt.getPoint());
        t_ninquilino.setText(String.valueOf(tablap.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_tablapMouseClicked

    private void busquedaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaiActionPerformed

    private void botoni7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoni7ActionPerformed
        // TODO add your handling code here:
        try
        {
            Conexion cn = new Conexion("jdbc:mysql://localhost/inmobiliaria", "root", "");
            Inmueble_data inmuebledata = new Inmueble_data(cn);
            //personadata.obtenerPersonasPorFiltro(filtro, busqueda.getText());

            List<Inmueble> inm = inmuebledata.obtenerInmueblesPorFiltro(filtro2, busquedai.getText());

            modelo2 = (DefaultTableModel) i.getModel();
            modelo2.setRowCount(0);
            Object[] fila = new Object[modelo2.getColumnCount()];

            for (int i = 0; i < inm.size(); i++) {
                fila[0] = inm.get(i).getId();
                fila[1] = inm.get(i).getDireccion();
                fila[2] = inm.get(i).getCantAmbientes();
                fila[3] = inm.get(i).getCosto();
                fila[4] = inm.get(i).getDisponibilidad();

                modelo2.addRow(fila);
            }

        }
        catch(Exception e)
        {
            e.getMessage();
        }
    }//GEN-LAST:event_botoni7ActionPerformed

    private void comboiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboiActionPerformed
        // TODO add your handling code here:
        if (comboi.getSelectedItem() == "Dirección")
        {
            filtro2 = "direccion";
        }
        if (comboi.getSelectedItem() == "Cantidad de ambientes")
        {
            filtro2 = "cantAmbientes";
        }
    }//GEN-LAST:event_comboiActionPerformed

    private void busquedapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedapActionPerformed

    private void iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseClicked
        // TODO add your handling code here:
        int seleccion = i.rowAtPoint(evt.getPoint());
        t_ninmueble.setText(String.valueOf(i.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_iMouseClicked

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        if (combo.getSelectedItem() == "Nombre")
        {
            filtro = "Nombre";
        }
        if (combo.getSelectedItem() == "Costo")
        {
            filtro = "costo";
        }
    }//GEN-LAST:event_comboActionPerformed

    private void botoon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoon1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Conexion cn = new Conexion("jdbc:mysql://localhost/inmobiliaria", "root", "");
            Alquiler alquile4 = new Alquiler();
            Alquiler_data alquilerdata = new Alquiler_data(cn);

            List<Alquiler> alq = alquilerdata.obtenerAlquileresPorFiltro(filtro, busqueda.getText());

            modelo = (DefaultTableModel) tabla.getModel();
            modelo.setRowCount(0);
            Object[] fila = new Object[modelo.getColumnCount()];

            for (int i = 0; i < alq.size(); i++) {
                fila[0] = alq.get(i).getId();
                fila[1] = alq.get(i).getNombre().toUpperCase();
                fila[2] = alq.get(i).getFechaInicio();
                fila[3] = alq.get(i).getFechaFin();
                fila[4] = alq.get(i).getCosto();

                modelo.addRow(fila);
            }

        }
        catch(Exception e)
        {
            e.getMessage();
        }
    }//GEN-LAST:event_botoon1ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int seleccion = tabla.rowAtPoint(evt.getPoint());
        t_nombrea.setText(String.valueOf(tabla.getValueAt(seleccion, 1)));
        t_ninicio.setText(String.valueOf(tabla.getValueAt(seleccion, 2)));
        t_nfin.setText(String.valueOf(tabla.getValueAt(seleccion, 3)));
        t_ncosto.setText(String.valueOf(tabla.getValueAt(seleccion, 4)));
    }//GEN-LAST:event_tablaMouseClicked

    private void t_ncostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ncostoKeyTyped
        // TODO add your handling code here:
               char c = evt.getKeyChar();
        
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_t_ncostoKeyTyped

    private void t_ninmuebleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ninmuebleKeyTyped
        // TODO add your handling code here:
               char c = evt.getKeyChar();
        
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_t_ninmuebleKeyTyped

    private void t_ninquilinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ninquilinoKeyTyped
        // TODO add your handling code here:
               char c = evt.getKeyChar();
        
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_t_ninquilinoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton b_salir;
    private javax.swing.JButton botoni7;
    private javax.swing.JButton botonp;
    private javax.swing.JButton botoon1;
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField busquedai;
    private javax.swing.JTextField busquedap;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> comboi;
    private javax.swing.JComboBox<String> combop;
    private javax.swing.JTable i;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel l_nambientes;
    private javax.swing.JLabel l_ncosto1;
    private javax.swing.JLabel l_ncosto2;
    private javax.swing.JLabel l_ninmueble;
    private javax.swing.JLabel l_ninquilino1;
    private javax.swing.JLabel l_nnombre;
    private javax.swing.JLabel l_nombrea;
    private javax.swing.JTextField t_ncosto;
    private javax.swing.JTextField t_nfin;
    private javax.swing.JTextField t_ninicio;
    private javax.swing.JTextField t_ninmueble;
    private javax.swing.JTextField t_ninquilino;
    private javax.swing.JTextField t_nnombre;
    private javax.swing.JTextField t_nombrea;
    private javax.swing.JTable tabla;
    private javax.swing.JScrollPane tablai;
    private javax.swing.JTable tablap;
    // End of variables declaration//GEN-END:variables
}
