/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author julit
 */
public class AgregarAlquiler extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarAlquiler
     */
    public AgregarAlquiler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_disponibilidad = new javax.swing.JTextField();
        l_disponibilidad = new javax.swing.JLabel();
        t_costo = new javax.swing.JTextField();
        l_costo = new javax.swing.JLabel();
        t_ambientes = new javax.swing.JTextField();
        l_ambientes = new javax.swing.JLabel();
        t_direccion = new javax.swing.JTextField();
        l_direccion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_disponibilidad1 = new javax.swing.JTextField();
        l_disponibilidad1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_disponibilidad.setBackground(new java.awt.Color(0, 51, 102));
        t_disponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        t_disponibilidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_disponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_disponibilidadActionPerformed(evt);
            }
        });
        getContentPane().add(t_disponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, -1));

        l_disponibilidad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_disponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        l_disponibilidad.setText("id_persona");
        getContentPane().add(l_disponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        t_costo.setBackground(new java.awt.Color(0, 51, 102));
        t_costo.setForeground(new java.awt.Color(255, 255, 255));
        t_costo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_costoActionPerformed(evt);
            }
        });
        getContentPane().add(t_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, -1));

        l_costo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_costo.setForeground(new java.awt.Color(255, 255, 255));
        l_costo.setText("Costo:");
        getContentPane().add(l_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        t_ambientes.setBackground(new java.awt.Color(0, 51, 102));
        t_ambientes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_ambientes.setForeground(new java.awt.Color(255, 255, 255));
        t_ambientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_ambientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ambientesActionPerformed(evt);
            }
        });
        getContentPane().add(t_ambientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        l_ambientes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_ambientes.setForeground(new java.awt.Color(255, 255, 255));
        l_ambientes.setText("Fecha de fin:");
        getContentPane().add(l_ambientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        t_direccion.setBackground(new java.awt.Color(0, 51, 102));
        t_direccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        t_direccion.setForeground(new java.awt.Color(255, 255, 255));
        t_direccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(t_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 110, 20));

        l_direccion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_direccion.setForeground(new java.awt.Color(255, 255, 255));
        l_direccion.setText("Fecha de inicio:");
        getContentPane().add(l_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alquileres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 110, 46));

        t_disponibilidad1.setBackground(new java.awt.Color(0, 51, 102));
        t_disponibilidad1.setForeground(new java.awt.Color(255, 255, 255));
        t_disponibilidad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_disponibilidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_disponibilidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(t_disponibilidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        l_disponibilidad1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        l_disponibilidad1.setForeground(new java.awt.Color(255, 255, 255));
        l_disponibilidad1.setText("id_persona");
        getContentPane().add(l_disponibilidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_direccionActionPerformed

    private void t_ambientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ambientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ambientesActionPerformed

    private void t_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_costoActionPerformed

    private void t_disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_disponibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_disponibilidadActionPerformed

    private void t_disponibilidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_disponibilidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_disponibilidad1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l_ambientes;
    private javax.swing.JLabel l_costo;
    private javax.swing.JLabel l_direccion;
    private javax.swing.JLabel l_disponibilidad;
    private javax.swing.JLabel l_disponibilidad1;
    private javax.swing.JTextField t_ambientes;
    private javax.swing.JTextField t_costo;
    private javax.swing.JTextField t_direccion;
    private javax.swing.JTextField t_disponibilidad;
    private javax.swing.JTextField t_disponibilidad1;
    // End of variables declaration//GEN-END:variables
}
