/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.*;
import java.awt.*;
import proyecto.xd.*;

/**
 *
 * @author julit
 */
public class ventanaPrincipal extends javax.swing.JFrame {
    private JFrame ventana;
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Inmobiliaria");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        inmuebles = new javax.swing.JMenu();
        i_agregar = new javax.swing.JMenuItem();
        i_borrar = new javax.swing.JMenuItem();
        i_actualizar = new javax.swing.JMenuItem();
        i_listar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregar = new javax.swing.JMenuItem();
        borrar = new javax.swing.JMenuItem();
        p_actualizar = new javax.swing.JMenuItem();
        p_listar = new javax.swing.JMenuItem();
        alquileres = new javax.swing.JMenu();
        a_agregar = new javax.swing.JMenuItem();
        a_borrar = new javax.swing.JMenuItem();
        a_actualizar = new javax.swing.JMenuItem();
        a_listar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        escritorio.setBackground(java.awt.SystemColor.activeCaption);
        escritorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        inmuebles.setText("Inmuebles");

        i_agregar.setText("Agregar");
        i_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_agregarActionPerformed(evt);
            }
        });
        inmuebles.add(i_agregar);

        i_borrar.setText("Borrar");
        i_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_borrarActionPerformed(evt);
            }
        });
        inmuebles.add(i_borrar);

        i_actualizar.setText("Actualizar");
        i_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_actualizarActionPerformed(evt);
            }
        });
        inmuebles.add(i_actualizar);

        i_listar.setText("Lista De Inmuebles");
        i_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_listarActionPerformed(evt);
            }
        });
        inmuebles.add(i_listar);

        jMenuBar1.add(inmuebles);

        jMenu2.setText("Clientes");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        agregar.setText("Agregar ");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jMenu2.add(agregar);

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jMenu2.add(borrar);

        p_actualizar.setText("Actualizar");
        p_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_actualizarActionPerformed(evt);
            }
        });
        jMenu2.add(p_actualizar);

        p_listar.setText("Lista de clientes");
        p_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_listarActionPerformed(evt);
            }
        });
        jMenu2.add(p_listar);

        jMenuBar1.add(jMenu2);

        alquileres.setText("Alquileres");

        a_agregar.setText("Agregar");
        a_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_agregarActionPerformed(evt);
            }
        });
        alquileres.add(a_agregar);

        a_borrar.setText("Borrar");
        a_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_borrarActionPerformed(evt);
            }
        });
        alquileres.add(a_borrar);

        a_actualizar.setText("Actualzar");
        a_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_actualizarActionPerformed(evt);
            }
        });
        alquileres.add(a_actualizar);

        a_listar.setText("Mostrar Alquileres");
        a_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_listarActionPerformed(evt);
            }
        });
        alquileres.add(a_listar);

        jMenuBar1.add(alquileres);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioCliente fc = new FormularioCliente();
        escritorio.add(fc);
        fc.setVisible(true);
        escritorio.moveToFront(fc);
    }//GEN-LAST:event_agregarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
       
        
        escritorio.removeAll();
        escritorio.repaint();
        BorrarCliente bc = new BorrarCliente();
        escritorio.add(bc);
        bc.setVisible(true);
        escritorio.moveToFront(bc);
    }//GEN-LAST:event_borrarActionPerformed

    private void p_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_actualizarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ActualizarCliente ac = new ActualizarCliente();
        escritorio.add(ac);
        ac.setVisible(true);
        escritorio.moveToFront(ac);
    }//GEN-LAST:event_p_actualizarActionPerformed

    private void i_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_agregarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AñadirInmueble ai = new AñadirInmueble();
        escritorio.add(ai);
        ai.setVisible(true);
        escritorio.moveToFront(ai);
    }//GEN-LAST:event_i_agregarActionPerformed

    private void i_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_borrarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BorrarInmueble ai = new BorrarInmueble();
        escritorio.add(ai);
        ai.setVisible(true);
        escritorio.moveToFront(ai);
    }//GEN-LAST:event_i_borrarActionPerformed

    private void i_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_actualizarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ActualizarInmueble ai = new ActualizarInmueble();
        escritorio.add(ai);
        ai.setVisible(true);
        escritorio.moveToFront(ai);
    }//GEN-LAST:event_i_actualizarActionPerformed

    private void a_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_agregarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarAlquiler aa = new AgregarAlquiler();
        escritorio.add(aa);
        aa.setVisible(true);
        escritorio.moveToFront(aa);
    }//GEN-LAST:event_a_agregarActionPerformed

    private void a_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_borrarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BorrarAlquiler aa = new BorrarAlquiler();
        escritorio.add(aa);
        aa.setVisible(true);
        escritorio.moveToFront(aa);
    }//GEN-LAST:event_a_borrarActionPerformed

    private void a_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_actualizarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ActualizarAlquiler aa = new ActualizarAlquiler();
        escritorio.add(aa);
        aa.setVisible(true);
        escritorio.moveToFront(aa);
    }//GEN-LAST:event_a_actualizarActionPerformed

    private void p_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_listarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoClientes lc = new ListadoClientes();
        escritorio.add(lc);
        lc.setVisible(true);
        escritorio.moveToFront(lc);
        
    }//GEN-LAST:event_p_listarActionPerformed

    private void i_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_listarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoInmuebles li = new ListadoInmuebles();
        escritorio.add(li);
        li.setVisible(true);
        escritorio.moveToFront(li);
    }//GEN-LAST:event_i_listarActionPerformed

    private void a_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_listarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoAlquileres la = new ListadoAlquileres();
        escritorio.add(la);
        la.setVisible(true);
        escritorio.moveToFront(la);
    }//GEN-LAST:event_a_listarActionPerformed

    private FormularioCliente c;
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem a_actualizar;
    private javax.swing.JMenuItem a_agregar;
    private javax.swing.JMenuItem a_borrar;
    private javax.swing.JMenuItem a_listar;
    private javax.swing.JMenuItem agregar;
    private javax.swing.JMenu alquileres;
    private javax.swing.JMenuItem borrar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem i_actualizar;
    private javax.swing.JMenuItem i_agregar;
    private javax.swing.JMenuItem i_borrar;
    private javax.swing.JMenuItem i_listar;
    private javax.swing.JMenu inmuebles;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem p_actualizar;
    private javax.swing.JMenuItem p_listar;
    // End of variables declaration//GEN-END:variables
}
