/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author julit
 */
public class ventanaPrincipal extends javax.swing.JFrame {
    private JFrame ventana;
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Inmobiliaria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inmuebles = new javax.swing.JMenu();
        i_agregar = new javax.swing.JMenuItem();
        i_borrar = new javax.swing.JMenuItem();
        i_actualizar = new javax.swing.JMenuItem();
        i_listar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregar = new javax.swing.JMenuItem();
        borrar = new javax.swing.JMenuItem();
        p_actualizar = new javax.swing.JMenuItem();
        p_listar = new javax.swing.JMenuItem();
        alquileres = new javax.swing.JMenu();
        a_agregar = new javax.swing.JMenuItem();
        a_borrar = new javax.swing.JMenuItem();
        a_actualizar = new javax.swing.JMenuItem();
        a_listar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        b_salir.setBackground(new java.awt.Color(0, 51, 102));
        b_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_salir.setForeground(new java.awt.Color(255, 255, 255));
        b_salir.setText("Salir");
        b_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inmobilaria");

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue.jpg"))); // NOI18N

        inmuebles.setText("Inmuebles");

        i_agregar.setText("Agregar");
        inmuebles.add(i_agregar);

        i_borrar.setText("Borrar");
        inmuebles.add(i_borrar);

        i_actualizar.setText("Actualizar");
        inmuebles.add(i_actualizar);

        i_listar.setText("Lista De Inmuebles");
        inmuebles.add(i_listar);

        jMenuBar1.add(inmuebles);

        jMenu2.setText("Clientes");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        agregar.setText("Agregar ");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jMenu2.add(agregar);

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jMenu2.add(borrar);

        p_actualizar.setText("Actualizar");
        jMenu2.add(p_actualizar);

        p_listar.setText("Lista de clientes");
        jMenu2.add(p_listar);

        jMenuBar1.add(jMenu2);

        alquileres.setText("Alquileres");

        a_agregar.setText("Agregar");
        alquileres.add(a_agregar);

        a_borrar.setText("Borrar");
        alquileres.add(a_borrar);

        a_actualizar.setText("Actualzar");
        alquileres.add(a_actualizar);

        a_listar.setText("Mostrar Alquileres");
        alquileres.add(a_listar);

        jMenuBar1.add(alquileres);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(b_salir))
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280)
                .addComponent(b_salir))
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        FormularioCliente fc = new FormularioCliente();
        this.add(fc);
        fc.setVisible(true);
    }//GEN-LAST:event_agregarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        BorrarCliente bc = new BorrarCliente();
        this.add(bc);
        bc.setVisible(true);
    }//GEN-LAST:event_borrarActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b_salirActionPerformed

    private FormularioCliente c;
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem a_actualizar;
    private javax.swing.JMenuItem a_agregar;
    private javax.swing.JMenuItem a_borrar;
    private javax.swing.JMenuItem a_listar;
    private javax.swing.JMenuItem agregar;
    private javax.swing.JMenu alquileres;
    private javax.swing.JButton b_salir;
    private javax.swing.JMenuItem borrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenuItem i_actualizar;
    private javax.swing.JMenuItem i_agregar;
    private javax.swing.JMenuItem i_borrar;
    private javax.swing.JMenuItem i_listar;
    private javax.swing.JMenu inmuebles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem p_actualizar;
    private javax.swing.JMenuItem p_listar;
    // End of variables declaration//GEN-END:variables
}
